/**
 * Copyright (c) 2026, United States Government, as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 *
 * All rights reserved.
 *
 * This software is licensed under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

#include "mujoco_ros2_control/mujoco_simulation.hpp"
#include "array_safety.h"

#include <chrono>
#include <cstddef>
#include <cstring>
#include <thread>

namespace mujoco_ros2_control
{
namespace mju = ::mujoco::sample_util;

namespace
{
const char* Diverged(int disableflags, const mjData* data)
{
  if (disableflags & mjDSBL_AUTORESET)
  {
    for (mjtWarning warning : { mjWARN_BADQACC, mjWARN_BADQVEL, mjWARN_BADQPOS })
    {
      if (data->warning[warning].number > 0)
      {
        return mju_warningText(warning, data->warning[warning].lastinfo);
      }
    }
  }
  return nullptr;
}
}  // namespace

void MujocoSimulation::initialize_force_buffers()
{
  const int force_buffer_size = 6 * mj_model_->nbody;

  xfrc_viewer_capture_.assign(force_buffer_size, 0.0);
  xfrc_plugin_desired_.assign(force_buffer_size, 0.0);
  xfrc_last_restore_.assign(force_buffer_size, 0.0);
}

bool MujocoSimulation::handle_ui_reset(
    mjtNum previous_sim_time)
{
  const bool reset_detected =
      mj_model_ &&
      mj_data_ &&
      previous_sim_time > 0.1 &&
      mj_data_->time < 0.01;

  if (!reset_detected)
  {
    return false;
  }

  RCLCPP_DEBUG(
      get_logger(),
      "UI reset detected "
      "(time jumped from %.3f to %.3f), "
      "applying initial state...",
      previous_sim_time,
      mj_data_->time);

  // reset_world_state() expects the previous simulation time.
  mj_data_->time = previous_sim_time;

  reset_world_state(true);

  // Preserve the viewer's timing/reset state.
  sim_->speed_changed = true;

  RCLCPP_INFO(
      get_logger(),
      "Successfully applied initial state after UI reset.");

  return true;
}

void MujocoSimulation::capture_viewer_forces(
    int force_buffer_size)
{
  const std::size_t force_buffer_bytes =
      static_cast<std::size_t>(force_buffer_size) *
      sizeof(mjtNum);

  const bool viewer_changed_forces =
      std::memcmp(
          mj_data_->xfrc_applied,
          xfrc_last_restore_.data(),
          force_buffer_bytes) != 0;

  if (viewer_changed_forces)
  {
    mju_copy(
        xfrc_viewer_capture_.data(),
        mj_data_->xfrc_applied,
        force_buffer_size);
  }
}

void MujocoSimulation::copy_control_inputs()
{
  // ctrl has one value per actuator.
  mju_copy(
      mj_data_->ctrl,
      mj_data_control_->ctrl,
      static_cast<int>(mj_model_->nu));

  // qfrc_applied has one value per degree of freedom.
  mju_copy(
      mj_data_->qfrc_applied,
      mj_data_control_->qfrc_applied,
      static_cast<int>(mj_model_->nv));
}

void MujocoSimulation::compose_external_forces(
    int force_buffer_size)
{
  // Begin with forces generated by dragging bodies in the viewer.
  mju_copy(
      mj_data_->xfrc_applied,
      xfrc_viewer_capture_.data(),
      force_buffer_size);

  // Add external forces requested by plugins.
  mju_addTo(
      mj_data_->xfrc_applied,
      xfrc_plugin_desired_.data(),
      force_buffer_size);
}

void MujocoSimulation::restore_external_forces_for_viewer(
    int force_buffer_size)
{
  compose_external_forces(force_buffer_size);

  // Save the exact value restored to xfrc_applied. This allows the next
  // iteration to detect whether the renderer changed the force array.
  mju_copy(
      xfrc_last_restore_.data(),
      mj_data_->xfrc_applied,
      force_buffer_size);
}

void MujocoSimulation::run_paused_simulation(
    int force_buffer_size)
{
  // Convert one keyboard step request into a pending simulation step.
  if (keyboard_step_requested_.exchange(false))
  {
    step_diverged_.store(false);
    pending_steps_.fetch_add(1);
  }

  if (pending_steps_.load() > 0)
  {
    copy_control_inputs();
    compose_external_forces(force_buffer_size);

    // Execute one requested step.
    mj_step(mj_model_, mj_data_);

    const char* divergence_message =
        Diverged(mj_model_->opt.disableflags, mj_data_);

    // Commit state before publishing the new simulation clock.
    mj_copyData(mj_data_control_, mj_model_, mj_data_);

    if (divergence_message)
    {
      pending_steps_.store(0);
      step_diverged_.store(true);

      mju::strcpy_arr(
          sim_->load_error,
          divergence_message);

      steps_cv_.notify_all();
    }
    else
    {
      restore_external_forces_for_viewer(force_buffer_size);

      sim_->AddToHistory();

      pending_steps_.fetch_sub(1);
      step_count_.fetch_add(1);

      steps_cv_.notify_all();
      update_sim_display();
    }

    publish_clock();

    if (pending_steps_.load() == 0)
    {
      sim_->speed_changed = true;
    }

    return;
  }

  // No step was requested. Keep the controller-facing state current.
  mj_copyData(mj_data_control_, mj_model_, mj_data_);

  restore_external_forces_for_viewer(force_buffer_size);

  // Update derived quantities and rendering without advancing time.
  mj_forward(mj_model_, mj_data_);

  sim_->speed_changed = true;
  update_sim_display();
}

bool MujocoSimulation::is_valid_command(mjtNum simulation_time)
{
  (void)simulation_time;

  // Temporary pacing delay while command-readiness synchronization is not implemented.
  std::this_thread::sleep_for(std::chrono::milliseconds(10));

  // No command sources are configured yet, so every timestep is valid.
  // Add cmd_vel and controller command-timing checks here later.
  return true;
}

}  // namespace mujoco_ros2_control
